### ISSUE TITLE
confirmacao sobre fechar

### ISSUE THREAD

**Issue by thr0w** [joseaugustoneto/h5-app.store#2]
closeProcess() - situacao normal onde force=false

p4/edit
p4.queryClose() {
  if (this.state.changed) 
    setState({confirmMode: true}
  else
    appstore.closeProcess(true) << force = true não chama queryClose
}

render
  if (this.confirMode)
    return <div><btn confirm={
                               appstore.closeProcess(true) << force = true não chama queryClose      
                         }
                        <btn cancelar={
                               setState(confirmMode=false);
                         }

**Comment by joseaugustoneto** [comment]
Antes de fechar a pagina do sistema ele pergunta se deseja sair da aplicação.

```javascript
window.addEventListener("beforeunload", function (event) {
     event.returnValue = "Deseja sair da aplicação? você pode perder dados!";
}.bind(this));
```
